import { useEffect, useState } from 'react';
import { Award, Calendar, Download, QrCode as QrCodeIcon } from 'lucide-react';
import QRCode from 'react-qr-code';
import jsPDF from 'jspdf';
import toast from 'react-hot-toast';
import Card from '../../components/ui/Card';
import Button from '../../components/ui/Button';
import api from '../../lib/api';
import { useAuthStore } from '../../store/authStore';

const Certificates = () => {
  const { user } = useAuthStore();
  const [certificates, setCertificates] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const loadCertificates = async () => {
      try {
        const { data } = await api.get('/student/certificates');
        setCertificates(data.certificates || []);
      } catch (error: any) {
        toast.error(error.response?.data?.message || 'Unable to load certificates');
      } finally {
        setLoading(false);
      }
    };
    loadCertificates();
  }, []);

  const downloadCertificate = (cert: any) => {
    const event = cert.eventId;
    const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });

    doc.setFillColor(248, 250, 252);
    doc.rect(0, 0, 297, 210, 'F');
    doc.setDrawColor(37, 99, 235);
    doc.setLineWidth(3);
    doc.rect(10, 10, 277, 190);
    doc.setFontSize(38);
    doc.setTextColor(37, 99, 235);
    doc.text('CERTIFICATE', 148.5, 42, { align: 'center' });
    doc.setFontSize(15);
    doc.setTextColor(75, 85, 99);
    doc.text('OF PARTICIPATION', 148.5, 54, { align: 'center' });
    doc.text('This is to certify that', 148.5, 78, { align: 'center' });
    doc.setFontSize(28);
    doc.setTextColor(17, 24, 39);
    doc.text(user?.name || 'Student', 148.5, 94, { align: 'center' });
    doc.setFontSize(14);
    doc.setTextColor(75, 85, 99);
    doc.text('has successfully participated in', 148.5, 110, { align: 'center' });
    doc.setFontSize(20);
    doc.setTextColor(37, 99, 235);
    doc.text(event?.title || 'Campus Event', 148.5, 126, { align: 'center' });
    doc.setFontSize(11);
    doc.setTextColor(75, 85, 99);
    doc.text(`Certificate No: ${cert.certificateNumber}`, 148.5, 146, { align: 'center' });
    doc.text(`Issued on: ${new Date(cert.issuedAt).toLocaleDateString()}`, 148.5, 158, { align: 'center' });
    doc.line(45, 176, 95, 176);
    doc.text('Organizer', 70, 184, { align: 'center' });
    doc.line(202, 176, 252, 176);
    doc.text('Principal', 227, 184, { align: 'center' });
    doc.save(`certificate-${cert.certificateNumber}.pdf`);
  };

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900 p-6">
      <div className="max-w-7xl mx-auto">
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-2">My Certificates</h1>
          <p className="text-gray-600 dark:text-gray-400">Certificates generated by admins from live attendance data.</p>
        </div>

        {loading ? (
          <Card className="text-center py-12">Loading certificates...</Card>
        ) : (
          <div className="grid md:grid-cols-2 gap-6">
            {certificates.map((cert) => (
              <Card key={cert._id} hover>
                <div className="flex items-start justify-between mb-4">
                  <div>
                    <h3 className="text-xl font-bold text-gray-900 dark:text-white">{cert.eventId?.title}</h3>
                    <p className="text-sm text-gray-600 dark:text-gray-400">Certificate No: {cert.certificateNumber}</p>
                  </div>
                  <Award className="w-8 h-8 text-yellow-500" />
                </div>
                <div className="space-y-2 mb-4 text-sm text-gray-600 dark:text-gray-400">
                  <div className="flex items-center gap-2">
                    <Calendar className="w-4 h-4" />
                    Issued on {new Date(cert.issuedAt).toLocaleDateString()}
                  </div>
                  <div className="flex items-center gap-2">
                    <QrCodeIcon className="w-4 h-4" />
                    {cert.qrVerificationCode}
                  </div>
                </div>
                <div className="flex gap-4 items-center mb-4">
                  <div className="bg-white p-2 rounded-lg">
                    <QRCode value={cert.qrVerificationCode} size={80} />
                  </div>
                  <p className="text-xs text-gray-600 dark:text-gray-400">Scan to verify this certificate.</p>
                </div>
                <Button onClick={() => downloadCertificate(cert)} className="w-full">
                  <Download className="w-4 h-4 mr-2" /> Download PDF
                </Button>
              </Card>
            ))}
          </div>
        )}

        {!loading && certificates.length === 0 ? (
          <Card className="text-center py-12">
            <Award className="w-16 h-16 text-gray-400 mx-auto mb-4" />
            <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-2">No certificates yet</h3>
            <p className="text-gray-600 dark:text-gray-400">Admins can generate certificates after attendance is marked.</p>
          </Card>
        ) : null}
      </div>
    </div>
  );
};

export default Certificates;
